### PR TITLE
Upgrades node-exporter to 0.18.0

### PR DESCRIPTION
**Pull request by JosephSalisbury**
Towards https://github.com/giantswarm/giantswarm/issues/6046

### CODE REVIEW

**Comment by JosephSalisbury** [comment]
I think I’m missing something here though:
```
2019-06-05 11:10:36
$ gsctl show release 8.1.0 | grep node-exporter
  node-exporter: 0.15.1
  node-exporter: Added separate podsecuritypolicy.
  node-exporter: Switched security context to non-root user.
  node-exporter: Use force when doing helm upgrades to fix failed releases.
```
@TheoBrigitte thoughts?

**Comment by kopiczko** [comment]
Don't you have to update version bundle somewhere?

**Comment by JosephSalisbury** [comment]
I think I have the right version of cluster-operator:
```
$ gsctl show release 8.1.0 | grep cluster-operator
  cluster-operator: 0.16.0
  cluster-operator: Added support for creating a cluster configmap for use by managed apps.
```

**Comment by kopiczko** [comment]
Update node-exporter component in service/controller/aws/v16/version_bundle.go

**Comment by JosephSalisbury** [comment]
Yeah, that’s it there. I don’t get why it’s not being picked up.

**Comment by JosephSalisbury** [comment]
There we go, I was on KVM, not AWS:
```
$ gsctl show release 8.1.0 | grep node
  node-exporter: 0.18.0
  node-exporter: Added separate podsecuritypolicy.
  node-exporter: Switched security context to non-root user.
  node-exporter: Use force when doing helm upgrades to fix failed releases.
```

**Comment by JosephSalisbury** [comment]
So, fishin’

**Pull request merged**
