### PR TITLE
Add new patch to release kube state metrics 1.5 to affected clusters

### PR DESCRIPTION
**Pull request by pipo02mix**
Towards https://github.com/giantswarm/giantswarm/issues/5009

### CODE REVIEW

**Comment by pipo02mix** [comment]
Tested on geckon it works fine

**Comment by pipo02mix** [comment]
Installations modified too https://github.com/giantswarm/installations/pull/621

**Comment by rossf7** [comment]
I'm a bit confused process wise here. Normally we do the copy and imports PR foo to add the patch version. There is then a PR with what is being changed.

The multiple PRs is a grind but until we have VOO we need it.  As is the PR is quite hard to review.

**Comment by rossf7** [comment]
It makes it a lot easier to see what is going on. For the copy and imports PRs you can just do pings no need to wait for approval.

https://github.com/giantswarm/giantswarm/blob/master/processes/new-version-bundle.md

For patch releases we do the code change and the wiring in a single PR. Also is this a KVM only change? If so you only need to copy pkg and the KVM controller.

**Comment by pipo02mix** [comment]
First one here https://github.com/giantswarm/cluster-operator/pull/361/files

**Pull request closed without merging**
