### PR TITLE
legacy: push-and-use-aliyun-repo2

### PR DESCRIPTION
**Pull request by calvix**
towards https://github.com/giantswarm/giantswarm/issues/8679

### CODE REVIEW

**Comment by calvix** [comment]
circle config is somehow fucky for legacy branch

**Comment by tfussell** [comment]
> circle config is somehow fucky for legacy branch

What's wrong with it?

**Comment by calvix** [comment]
> What's wrong with it?

It doesn't build any images nor push to catalog on PR

**Comment by calvix** [comment]
OK this works :) merging

**Pull request merged**
