### PR TITLE
Use release.Revision in Helm chart for Helm 3 support.

### PR DESCRIPTION
**Pull request by rossf7**
Towards https://github.com/giantswarm/giantswarm/issues/10098

## Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by rossf7** [comment]
Tested on `ginger`.

**Comment by xh3b4sd** [comment]
Please merge master. The changelog does not look right. `2.1.8` is already out.

**Comment by rossf7** [comment]
@xh3b4sd Ack. Will check.

**Comment by rossf7** [comment]
@xh3b4sd Fixed. PTAL

**Pull request merged**
