### PR TITLE
Clean up after cluster is deleted

### PR DESCRIPTION
**Pull request by kubasobon**
Towards https://github.com/giantswarm/giantswarm/issues/16451

## Checklist

- [ ] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Review by QuentinBisson — APPROVED** [review]

**Comment by kubasobon** [comment]
I was too quick, I want to add more to this PR.

**Comment by kubasobon** [comment]
Changes made:
- remove ConfigMaps (return empty list as desired) after Cluster CR is deleted - works fine
- remove App CRs (return empty list as desired) after Cluster CR is deleted - issues described below

Here's the issue I'm experiencing:
- App CRs are deleted (`deletionTimestamp` is set) but still pending because of `operatorkit.giantswarm.io/app-operator-app` finalizer 
- cluster-operator's `appfinalizer` controller removes finalizers for all App CRs except for `app-operator-<clusterid>`
- logs prove that finalizers have been succesfully deleted
- half of the App CRs are deleted, since finalizers are gone; the other half has finalizers for some reason
- `app-operator-<clusterid>` is deleted, since Pod is cleaned up
- the stuck App CRs are never deleted, since the only app-operator which could remove the finalizer is gone

### Leftover apps
```
NAME                 VERSION                                           LAST DEPLOYED   STATUS
calico               0.2.0                                             44m             deployed
cert-exporter        1.6.0                                             44m             deployed
cert-manager         2.4.1                                             44m             deployed
chart-operator       2.11.0-a332e330b9a1e5a12e8484038f9120f243c578fe   44m             deployed
cluster-autoscaler   1.19.1                                            44m             deployed
coredns              1.2.0                                                             not-installed
external-dns         2.1.1                                             42m             deployed
```

### `cluster-operator` debug log messages

<details>

```
computed 1 ConfigMaps to update
updating ConfigMap `kubacl-cluster-values` in namespace `kubacl`
updated ConfigMap `kubacl-cluster-values` in namespace `kubacl`
finding apps to remove finalizers for
found 12 apps to remove finalizers for
removing finalizer for app `calico`
KUBA: `calico` - finalizers: [operatorkit.giantswarm.io/app-operator-app]
KUBA: `calico` - index: 0
KUBA: `calico` - result finalizers: []
removed finalizer for app `calico`
removing finalizer for app `cert-exporter`
KUBA: `cert-exporter` - finalizers: [operatorkit.giantswarm.io/app-operator-app]
KUBA: `cert-exporter` - index: 0
KUBA: `cert-exporter` - result finalizers: []
removed finalizer for app `cert-exporter`
removing finalizer for app `cert-manager`
KUBA: `cert-manager` - finalizers: [operatorkit.giantswarm.io/app-operator-app]
KUBA: `cert-manager` - index: 0
KUBA: `cert-manager` - result finalizers: []
removed finalizer for app `cert-manager`
removing finalizer for app `chart-operator`
KUBA: `chart-operator` - finalizers: [operatorkit.giantswarm.io/app-operator-app]
KUBA: `chart-operator` - index: 0
KUBA: `chart-operator` - result finalizers: []
removed finalizer for app `chart-operator`
removing finalizer for app `cluster-autoscaler`
KUBA: `cluster-autoscaler` - finalizers: [operatorkit.giantswarm.io/app-operator-app]
KUBA: `cluster-autoscaler` - index: 0
KUBA: `cluster-autoscaler` - result finalizers: []
removed finalizer for app `cluster-autoscaler`
removing finalizer for app `coredns`
KUBA: `coredns` - finalizers: [operatorkit.giantswarm.io/app-operator-app]
KUBA: `coredns` - index: 0
KUBA: `coredns` - result finalizers: []
removed finalizer for app `coredns`
removing finalizer for app `external-dns`
KUBA: `external-dns` - finalizers: [operatorkit.giantswarm.io/app-operator-app]
KUBA: `external-dns` - index: 0
KUBA: `external-dns` - result finalizers: []
removed finalizer for app `external-dns`
removing finalizer for app `kiam`
KUBA: `kiam` - finalizers: [operatorkit.giantswarm.io/app-operator-app]
KUBA: `kiam` - index: 0
KUBA: `kiam` - result finalizers: []
removed finalizer for app `kiam`
removing finalizer for app `kube-state-metrics`
KUBA: `kube-state-metrics` - finalizers: [operatorkit.giantswarm.io/app-operator-app]
KUBA: `kube-state-metrics` - index: 0
KUBA: `kube-state-metrics` - result finalizers: []
removed finalizer for app `kube-state-metrics`
removing finalizer for app `metrics-server`
KUBA: `metrics-server` - finalizers: [operatorkit.giantswarm.io/app-operator-app]
KUBA: `metrics-server` - index: 0
KUBA: `metrics-server` - result finalizers: []
removed finalizer for app `metrics-server`
removing finalizer for app `net-exporter`
KUBA: `net-exporter` - finalizers: [operatorkit.giantswarm.io/app-operator-app]
KUBA: `net-exporter` - index: 0
KUBA: `net-exporter` - result finalizers: []
removed finalizer for app `net-exporter`
removing finalizer for app `node-exporter`
KUBA: `node-exporter` - finalizers: [operatorkit.giantswarm.io/app-operator-app]
KUBA: `node-exporter` - index: 0
KUBA: `node-exporter` - result finalizers: []
removed finalizer for app `node-exporter`
finding apps for tenant cluster `kubacl`
found 13 apps for tenant cluster `kubacl`
finding configMaps in namespace `kubacl`
found 2 configMaps in namespace `kubacl`
finding secrets in namespace `kubacl`
found 10 secrets in namespace `kubacl`
deleting apps for tenant cluster `kubacl`
computing App CRs to create 
computed 0 App CRs to create
computing App CRs to delete
computed 13 App CRs to delete
computing App CRs to update
computed 0 App CRs to update
deleting App CR `app-operator-kubacl` in namespace `kubacl`
deleted App CR `app-operator-kubacl` in namespace `kubacl`
deleting App CR `calico` in namespace `kubacl`
deleted App CR `calico` in namespace `kubacl`
deleting App CR `cert-exporter` in namespace `kubacl`
deleted App CR `cert-exporter` in namespace `kubacl`
deleting App CR `cert-manager` in namespace `kubacl`
deleted App CR `cert-manager` in namespace `kubacl`
deleting App CR `chart-operator` in namespace `kubacl`
deleted App CR `chart-operator` in namespace `kubacl`
deleting App CR `cluster-autoscaler` in namespace `kubacl`
deleted App CR `cluster-autoscaler` in namespace `kubacl`
deleting App CR `coredns` in namespace `kubacl`
deleted App CR `coredns` in namespace `kubacl`
deleting App CR `external-dns` in namespace `kubacl`
deleted App CR `external-dns` in namespace `kubacl`
deleting App CR `kiam` in namespace `kubacl`
deleted App CR `kiam` in namespace `kubacl`
deleting App CR `kube-state-metrics` in namespace `kubacl`
deleted App CR `kube-state-metrics` in namespace `kubacl`
deleting App CR `metrics-server` in namespace `kubacl`
deleted App CR `metrics-server` in namespace `kubacl`
deleting App CR `net-exporter` in namespace `kubacl`
deleted App CR `net-exporter` in namespace `kubacl`
deleting App CR `node-exporter` in namespace `kubacl`
deleted App CR `node-exporter` in namespace `kubacl`
finding cluster config maps in namespace `kubacl`
found 1 config maps in namespace `kubacl`
deleting cluster ConfigMap for tenant cluster `kubacl`
deleting ConfigMap `kubacl-cluster-values` in namespace `kubacl`
deleted ConfigMap `kubacl-cluster-values` in namespace `kubacl`
removing finalizer `operatorkit.giantswarm.io/cluster-operator-cluster-controller`
removed finalizer `operatorkit.giantswarm.io/cluster-operator-cluster-controller`
```
</details>

Using extra debug logs from [here](https://github.com/giantswarm/cluster-operator/pull/1379/commits/cd63f05a4f00db5824fb82f07a210547a22325aa)

[full-cluster-operator.log](https://github.com/giantswarm/cluster-operator/files/6206054/full-cluster-operator.log)
[full-app-operator.log](https://github.com/giantswarm/cluster-operator/files/6206055/full-app-operator.log)
[leftover-apps.yaml.txt](https://github.com/giantswarm/cluster-operator/files/6206065/leftover-apps.yaml.txt)

**Comment by MarcelMue** [comment]
Maybe I am missing it but do we know what deleted app-operator?

**Comment by kubasobon** [comment]
@MarcelMue `cluster-operator`

**Comment by tomahawk28** [comment]
>  It does it once, so I'm not sure why the finalizers are still there. Is it a race between the app-operator and cluster-operator?

@kubasobon I think app-operator had had a reconciliation once more before it got deleted. I just checked the order of resources and `appFinalizer` is the next reconciliation after `app` 
https://github.com/giantswarm/cluster-operator/blob/1e28be9ce6ec5fea99ed88027c9b93d6cb6ac4c2/service/controller/cluster.go#L594-L595

What do you think waiting until app-operator per cluster namespace will have cleaned up and delete all finalizers in `appFinalizer` resource? If you are busy with other things in CAPI, I can implement that in this branch.

**Comment by kubasobon** [comment]
@tomahawk28 go ahead :smile: I was trying to figure out why are some resources orphaned, but the CAPI month ended. I got pulled back to other things rn. Give me a shout if something I've changed doesn't make sense or you just need a hand.

**Comment by tomahawk28** [comment]
@kubasobon Can you test this again? I don't know how to test this manually. :)

**Comment by kubasobon** [comment]
I merged pre-_config-controller_ `master` branch to side-step some build issues.

@tomahawk28 Sorry I took so long, I missed the notification.
FYI the testing procedure is straightforward:
- create a custom release with changed `cluster-operator` version
- create a test cluster
- wait until the cluster is created, check if apps in WC namespace are deployed
- delete WC
- everything in WC namespace should get deleted (`cm,secret,app`), then the namespace should go as well

The issue is I do not know if we are running CAPI release on any of test installations. Do you know where I could test this?

**Comment by anvddriesch** [comment]
I believe you can test this in `ginger`.

**Comment by kubasobon** [comment]
I'm trying to test on `ginger`, but I'm hitting AWS permission issues and I'm unsure where/what to check:
```
I0429 12:26:22.375474       1 awscluster_controller.go:196] controllers/AWSCluster "msg"="Reconciling AWSCluster" "awsCluster"="kuba" "cluster"="kuba" "namespace"="kuba" 
E0429 12:26:22.502966       1 awscluster_controller.go:213] controllers/AWSCluster "msg"="failed to reconcile network" "error"="failed to describe VPCs: failed to query ec2 for VPCs: UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: 167524d9-8fe4-4b6b-a20a-a276ca571689" "awsCluster"="kuba" "cluster"="kuba" "namespace"="kuba" 
```

**Comment by anvddriesch** [comment]
Hey, sorry for not seeing this earlier. In case you are still facing this issue: it's likely because we introduced multi-tenancy. The controller user is in the management account but the resources are created in the workload account. For this to work you need to set up a `AWSClusterRoleIdentity` for your cluster. A few exist in `ginger` already so you can probably just use one or make another one as a copy of what's already there. It looks like this:

```apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSClusterRoleIdentity
metadata:
  name: kuba
  namespace: kuba
  labels:
    release.giantswarm.io/version: 20.0.0-v1alpha3
    giantswarm.io/cluster: kuba
    cluster.x-k8s.io/cluster-name: kuba
spec:
  allowedNamespaces:
    list:
    - kuba
  roleARN: arn:aws:iam::$WORKLOADACCOUNT:role/ginger-capa-controller
```

Then you need to set a reference to this identity in your `AWSCluster` CR:

```
spec:
...
  identityRef:
    kind: AWSClusterRoleIdentity
    name: kuba
```

**Comment by kubasobon** [comment]
@anvddriesch Thanks, I'm sure this will help :) I'll test ASAP.

**Comment by anvddriesch** [comment]
ping me if there are more problems.

**Comment by kubasobon** [comment]
Tested on _ginger_. All the resources are cleaned up nicely :broom:: 
- ConfigMaps
- Secrets
- Apps
- All CAPI resources.

I had to manually delete my cluster's namespace, but that's all.
@tomahawk28 Your changes made the dream work :tada: 
@anvddriesch thank you for helping me out whenever I got lost :trophy:

**Review by anvddriesch — APPROVED** [review]

**Comment by anvddriesch** [comment]
Awsome!

**Review by MarcelMue — APPROVED** [review]
Nice!

**Pull request merged**
