### PR TITLE
Notes annotation for cluster configmaps

### PR DESCRIPTION
**Pull request by rossf7**
We had some cases of users editing the cluster configmaps managed by cluster-operator. They should instead create a user values configmap.

We already add this annotation to the configmaps and secrets in the tenant cluster that are managed by app-operator.

## Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by omegas27** [comment]
I like this :) Also, I am wondering if we should not prevent mutations of those CM with OPA the same way we do not allow users to change the giantswarm labels? WDYT?

**Comment by rossf7** [comment]
> I am wondering if we should not prevent mutations of those CM with OPA the same way we do not allow users to change the giantswarm labels?

I need to get deeper into what we're doing with OPA but that makes sense to me. It would provider better feedback to the user.

@oponder Could we track this in the UX improvements you're speccing?

**Comment by oponder** [comment]
@ross yup! Thanks for the mention

**Comment by ross** [comment]
> @ross yup! Thanks for the mention

Think you wanted @rossf7 :grin:

**Comment by oponder** [comment]
@ross Heh sorry. 😓 Probably not the first time this happens. My bad, and thanks for letting me know :+1:

**Comment by rossf7** [comment]
Finally back to this. 🎉 Tested on `gauss`.

```
kubectl get cm -n 5ba69  5ba69-cluster-values -o yaml
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    giantswarm.io/notes: DO NOT EDIT. Values managed by cluster-operator.
  name: 5ba69-cluster-values
  namespace: 5ba69
```

**Pull request merged**
