### PR TITLE
Freeze 0.3.0 version bundle (v3) for AWS

### PR DESCRIPTION
**Pull request by rossf7**
Towards giantswarm/giantswarm#1902

### CODE REVIEW

**Comment by kopiczko** [comment]
Why v3 was WIP for so long?

**Comment by rossf7** [comment]
@kopiczko Managed services rollout got slowed down by conferences and travel. Not sure about k8sd migration but I think it's had less priority.

We still need to deploy node-exporter and ingress-controller via charts. So next WIP release won't be open as long.

**Comment by kopiczko** [comment]
@rossf7 I was thinking it's aws-operator repo and this is made non-WIP after we have v11 :D
Sorry for the confusion. I don't have any issues with you velocity <3

**Comment by rossf7** [comment]
@kopiczko Jeje, OK that makes sense! Thanks for the clarification! <3.

**Pull request merged**
