### PR TITLE
updates vendor deps

### PR DESCRIPTION
**Pull request by xh3b4sd**

### CODE REVIEW

**Comment by xh3b4sd** [comment]
@rossf7 can you check the build errors? I think you missed something with your latest changes. Or am I dumb?

**Comment by rossf7** [comment]
Yes this is my helmclient changes. I need to get rid of the mock_test.go files. I can take care of sorting the deps here and I'll also do chart-operator.

**Comment by rossf7** [comment]
>  I'll also do chart-operator.

You've already done it ❤️.

**Comment by xh3b4sd** [comment]
Just give me a shout when you are done.

**Comment by rossf7** [comment]
Done in #355. This can be closed.

**Comment by xh3b4sd** [comment]
@rossf7 is this sorted? I think you fixed that in another PR? Can you confirm and close?

**Comment by rossf7** [comment]
Yes was done in #355. Closing.

**Pull request closed without merging**
