### PR TITLE
Remove unused awsconfig, azureconfig and kvmconfig resources

### PR DESCRIPTION
**Pull request by rossf7**
This came up in the review of https://github.com/giantswarm/giantswarm/pull/5405. These resources are not used and the approach has changed because we don't want to have provider specific resources.

I'd like to get this in before we ship v11.

### CODE REVIEW

**Comment by rossf7** [comment]
Before we can have single controller there is still some tidying up on the apps side. We use it to inject provider specific state like only running the cluster-autoscaler on AWS.

e.g.
https://github.com/giantswarm/cluster-operator/blob/38bcd7dbec6a0fde186b2cbe81e6cd9e13ef4830/service/controller/aws/v11/key/key.go#L16
https://github.com/giantswarm/cluster-operator/blob/38bcd7dbec6a0fde186b2cbe81e6cd9e13ef4830/service/controller/aws/v11/resource/configmap/desired.go#L42

This will go away when we move the apps to the release CRs.

**Comment by xh3b4sd** [comment]
Ok, how is the differentiation then made? Any vague ETA?

**Comment by rossf7** [comment]
@xh3b4sd I think it will be some time in Q2. Our current phase is supporting VOO and optional apps for customers. After that our next phase is migrating existing apps from chartconfig CRs to app CRs. 

But I don't think this needs to block flattening to a single controller. There isn't much per provider state and even a simple case statement would work. It would likely make the code more understandable as all the code is in the same resources.

**Comment by xh3b4sd** [comment]
I see. I was thinking about node pools and we would like to drop most of the old CRs. We have to support the `*ClusterConfig` CRs though as long as `cluster-operator` needs them.

**Pull request merged**
