### PR TITLE
vendor update: helmclient

### PR DESCRIPTION
**Pull request by tomahawk28**
Toward giantswarm/giantswarm#4953
it would enable metrics from helmclient in cluster-operator.

### CODE REVIEW

**Comment by MarcelMue** [comment]
I see 0 changes in this PR - what is going on here?

**Comment by sslavic** [comment]
@tomahawk28 I guess you wanted to rebase this branch commit on top of master changes.

**Comment by tomahawk28** [comment]
I have no idea what happen after rebase, I will check this PR, sorry.

**Comment by tomahawk28** [comment]
Looks like someone already update helmclient at some point. that's why it have zero change :)

**Comment by tomahawk28** [comment]
It had been merged already by https://github.com/giantswarm/cluster-operator/pull/473. 
We can close this.

**Pull request closed without merging**
