### PR TITLE
Fix migration logic when creating app CRs

### PR DESCRIPTION
**Pull request by rossf7**
Towards https://github.com/giantswarm/giantswarm/issues/10211

## Checklist

- [ ] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by oponder** [comment]
Tested it a couple of time on KVM, I am a bit confused by other errors which I think are not related 

(the ingress-controller seems to run into RBAC permission issues after upgrading from 9.0.0 to 9.0.2 or my temporary 9.0.3 release)

I'm not sure how to trigger the exact timing issue that the customer noticed. Do I have to create a `nginx-ingress-controller-user-values` in the `kube-system` namespace before `chart-operator` and such arrive on the cluster? 

I tried creating the configmap after things were already up and running and nothing bad happened.

**Comment by rossf7** [comment]
Thanks and maybe check with Ludacris on the RBAC issues? They might have seen it before.

> I'm not sure how to trigger the exact timing issue that the customer noticed. Do I have to create a nginx-ingress-controller-user-values in the kube-system namespace before chart-operator and such arrive on the cluster?

Yes the timing is tricky but you could scale down the cluster-operator pod. So you can create the configmap in the tenant before cluster-operator connects.

I think the problem was caused because the customer had automation that created the configmap once the cluster was up. This ran before cluster-operator had connected.

**Comment by oponder** [comment]
Nice idea, testing that now.

**Comment by oponder** [comment]
Ok phew! I think it is working as intended. I tested the upgrade path, I also tested a brand new cluster where there is a `nginx-ingress-controller-user-values`, and the ingress controller came up fine!

I still have a reservation on `geckon` where the `11.3.2` release is being reconciled by the cluster operator in this branch in case you want to fiddle with anything still.

But as far as verifying this works, on KVM, it seems good.

**Comment by rossf7** [comment]
@oponder Thank you again for testing this. I took a look on geckon and all looks fine so feel free to delete the cluster.

I'll get this submitted for review.

**Comment by rossf7** [comment]
@oponder Thanks going with this.

The go routine and channel is to align with the other migration resources. I missed this when I added the logic originally.

Without it when tenant clusters are down or unresponsive the operator can block for up to 30 secs. This prevents other CRs from being reconciled. So we use a short timeout of 3 secs and retry later.

Same code in the appmigration resource.
https://github.com/giantswarm/cluster-operator/blob/a54f6d72291947fd03ebdf08ffe6f2c74ba2aab5/service/controller/resource/appmigration/create.go#L74-L90

**Comment by oponder** [comment]
Ok interesting! I would've expected to change the timeout maybe on the kubernetes client itself instead?  

But yeah I get it, there are probably tradeoffs here that I'm not aware of! Thanks for explaining!

**Comment by rossf7** [comment]
> I would've expected to change the timeout maybe on the kubernetes client itself instead?

Yes it should be easier to do this with the kubernetes client.

In 1.18 they are adding context to all the methods and then I think we could use context.WithCancel which would be a lot simpler.

**Pull request merged**
