### PR TITLE
v6patch1: wiring

### PR DESCRIPTION
**Pull request by pipo02mix**

### CODE REVIEW

**Comment by rossf7** [comment]
The version in version_bundle.go needs to be bumped and the changelog updated. Otherwise this looks good.

**Comment by pipo02mix** [comment]
ok I added those changes and the channel here so this will be the final PR. I was doubting to do an extra with the changes but it is just the channel increment

**Comment by pipo02mix** [comment]
Tested the upgrade. It worked fine PTAL

**Comment by rossf7** [comment]
I don't see the channel change. Don't we need it?

**Comment by pipo02mix** [comment]
Partial commit did not work fine. Good catch! now

**Pull request merged**
