### PR TITLE
v17/key: set 0.4-stable channel for node-exporter

### PR DESCRIPTION
**Pull request by kopiczko**
Towards https://github.com/giantswarm/giantswarm/issues/6132.

### CODE REVIEW

**Comment by tomahawk28** [comment]
Why I can't see any `0-*-stable` channel in here? https://quay.io/application/giantswarm/kubernetes-node-exporter-chart?tab=channels

**Comment by rossf7** [comment]
0-3-stable is on the 2nd page but I don't see 0-4-stable.

**Comment by kopiczko** [comment]
Does it need to be created manually?

**Comment by kopiczko** [comment]
Here's my PR setting 0.4.0: https://github.com/giantswarm/kubernetes-node-exporter/pull/41

**Comment by rossf7** [comment]
It should have been created automatically when your PR was merged. Looks like it was because this e2e test failed. 

https://circleci.com/gh/giantswarm/kubernetes-node-exporter/511

We should just remove the migration e2e tests as they are no longer needed. I'll add a note to the sig-releng board. 

I would try rerunning CI. If it passes the channel be created.

**Comment by rossf7** [comment]
We talked in the sync and I created https://github.com/giantswarm/giantswarm/issues/6292 to remove the migration tests from the repos.

I'll remove node-exporter first and this will create the release channel.

cc @kopiczko

**Pull request merged**
