### PR TITLE
Fix go fmt

### PR DESCRIPTION
**Pull request by TheoBrigitte**
Fixed go format using: `$ find ./* -maxdepth 0 -type d |grep -v vendor|xargs gofmt -w`

### CODE REVIEW

**Comment by kopiczko** [comment]
Why not `go fmt ./...`. It skips vendor from 1.10 if not earlier.

**Comment by TheoBrigitte** [comment]
A "significant" [change](https://github.com/golang/go/commit/542ea5ad91367d2b40589942cc5757a4d5f43f97) as been introduced in `gofmt` v1.11.1, therefore our CI breaks since it uses v1.10.4.

This sounds like a much bigger issue, since we would have to re-format all our repository.

**Comment by kopiczko** [comment]
Looks like time to update architect.

**Comment by kopiczko** [comment]
That's a good finding. Please also announce in #news-dev.

**Pull request merged**
