### PR TITLE
Add CHANGELOG.md

### PR DESCRIPTION
**Pull request by sslavic**
## Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by sslavic** [comment]
Going with a ping

**Comment by tfussell** [comment]
@sslavic I was thinking it might be better to keep only one `CHANGELOG` on `master`. What do you think?

**Comment by sslavic** [comment]
@tfussell I doubt https://intranet.giantswarm.io/docs/dev-and-releng/how-to-release-a-project/ can work like that. It tried to update file on same branch being released and failed since it didn't exist on legacy even though it was there on master https://github.com/giantswarm/cluster-operator/runs/858714049

@giantswarm/team-biscuit what say you?

**Comment by kopiczko** [comment]
I'll take care to fix workflow for non-master branches and URLs but the question is if really want to have all versions in `master` CHANGELOG.md? That would complicate things a lot. Not only for automation but also for humans. How would you add changes you've made to the changelog?

**Comment by tfussell** [comment]
Etcd (e.g. https://github.com/etcd-io/etcd/blob/master/CHANGELOG-3.3.md) and Kubernetes (e.g. https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.17.md) both keep a changelog for each minor release on `master`. I'm not sure how they do it, maybe with some automation. I'm okay with keeping it in `legacy` if it complicates things though--this just came up when I was working on parsing changelogs recently.

**Comment by kopiczko** [comment]
>  a changelog for each minor release on master

How about bug-fixes?

In case of K8s it is very easy because they are on `1.x.x` for a long time.

Complete list of releases can still be found in GH releases page. We should link to changelogs from there.

>  I'm okay with keeping it in legacy if it complicates things though

Legacy branches are exception here. Once we get rid of them we shouldn't have that problem because all minors should initiate in master which is not the case now. So I'd prefer to have things like they are for practical reasons.

**Comment by tfussell** [comment]
> Legacy branches are exception here. Once we get rid of them we shouldn't have that problem because all minors should initiate in master which is not the case now. So I'd prefer to have things like they are for practical reasons.

Sounds good to me.

**Pull request merged**
