### PR TITLE
Legacy net exporter update to 1.6.0

### PR DESCRIPTION
**Pull request by jgsqware**

### CODE REVIEW

**Comment by sslavic** [comment]
@jgsqware why were nginx IC changelog entries removed?

**Comment by kopiczko** [comment]
> @jgsqware why were nginx IC changelog entries removed?

@sslavic this was a mistake triggered by this comment https://github.com/giantswarm/cluster-operator/pull/902#issuecomment-579685216.

**Comment by kopiczko** [comment]
I'll restore them.

**Comment by kopiczko** [comment]
> I'll restore them.

Or rather not because it's already released...

**Comment by MarcelMue** [comment]
@kopiczko Wait so was this my confusion? I thought the ones you posted to link to were supposed to be deleted.
Or am I confused now?

**Comment by kopiczko** [comment]
@MarcelMue we assumed we should wipe out changelogs also in legacy branch. It isn't your fault at all.

**Comment by kopiczko** [comment]
See https://github.com/giantswarm/releases/pull/83

**Pull request merged**
