### PR TITLE
legacy: Reset changelogs, bump to next dev version

### PR DESCRIPTION
**Pull request by tfussell**

### CODE REVIEW

**Comment by sslavic** [comment]
@tfussell @MarcelMue changelog was reset for aws only; was there a reason for not resetting changelog for kvm and azure too?

**Comment by MarcelMue** [comment]
@sslavic I think we simply forgot to remove those. I can supply a PR.

**Comment by sslavic** [comment]
@MarcelMue no need, thanks. I'm adding next nginx release changelog so will clean up kvm+azure in the same go

**Comment by tfussell** [comment]
That's my mistake. Thanks for catching it.

**Pull request merged**
