### PR TITLE
store encryptionkey in default namespace

### PR DESCRIPTION
**Pull request by anvddriesch**
Towards: https://github.com/giantswarm/giantswarm/issues/12647
When creating a cluster in another namespace I want to keep the decryptionkey in `default` with the other secrets. (For testing purposes. But generally we should discuss where we want to store secrets when creating clusters in other namespaces)

## Checklist

- [ ] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by njuettner** [comment]
Does it make sense to put it into the giantswarm namespace instead of using the default namespace? I can imagine it would be easier to restrict only one namespace, WDYT?

**Comment by paurosello** [comment]
This secret is not related to the "AWS Credential" secret right? Asking because that one should be in the org namespace to allow discoverability for our customers in the  "--credential" attribute in kubectl-gs

**Comment by anvddriesch** [comment]
The thing is that right now most secrets will be created in the `default` namespace.
For a cluster created in the namespace `test` the secrets are stored as follows:

```
default                 shark-api                                                              Opaque                                3      6h49m
default                 shark-app-operator-api                                                 Opaque                                3      6h49m
default                 shark-aws-operator-api                                                 Opaque                                3      6h49m
default                 shark-calico-etcd-client                                               Opaque                                3      6h49m
default                 shark-cluster-operator-api                                             Opaque                                3      6h49m
default                 shark-etcd1                                                            Opaque                                3      86m
default                 shark-etcd2                                                            Opaque                                3      86m
default                 shark-etcd3                                                            Opaque                                3      86m
default                 shark-node-operator                                                    Opaque                                3      6h49m
default                 shark-prometheus                                                       Opaque                                3      6h49m
default                 shark-service-account                                                  Opaque                                3      6h49m
default                 shark-worker                                                           Opaque                                3      6h49m
shark-prometheus        additional-scrape-configs                                              Opaque                                1      6h46m
shark-prometheus        cluster-certificates                                                   Opaque                                3      6h46m
shark-prometheus        default-token-scp9m                                                    kubernetes.io/service-account-token   3      6h52m
shark-prometheus        prometheus-shark                                                       Opaque                                1      6h46m
shark-prometheus        prometheus-shark-tls-assets                                            Opaque                                0      6h46m
shark                   default-token-2txl7                                                    kubernetes.io/service-account-token   3      6h52m
shark                   shark-kubeconfig                                                       Opaque                                1      6h49m
test                    shark-encryption                                                       Opaque                                1      142m
```
As you can see, the `encryption` secret is the only one stored in `test` right now. If we move it back to `default` (what this PR does) , we can create a working cluster in any namespace, but we still need to figure out where we want to keep the secrets to limit access.

**Comment by xh3b4sd** [comment]
Why wouldn't we want to keep all Tenant Cluster resources in the same namespace?

**Comment by anvddriesch** [comment]
I think the resources which are already in the cluster-id namespaces should probably stay there. As for the ones which are now in `default`, we could probably move all of them to the namespace the cluster is created in. However, I am not sure what the implications of that would be.

**Comment by xh3b4sd** [comment]
I guess there are two different cases that we should not mix. Existing clusters and new clusters. I would assume the simplest solution for the future would be to have all resources associated with a cluster in one namespace. How we migrate existing clusters is a different question IMO.

**Comment by anvddriesch** [comment]
I didn't mean for existing clusters, I meant for future clusters. I understand that we want to move from one namespace for everything to organization-wide namespaces. But why would we want to switch from a cluster-wide namespace to organization-wide?

**Comment by xh3b4sd** [comment]
Hey, what about this PR? Can we push this over the finish line? 😄

**Comment by anvddriesch** [comment]
Ah sorry. I should have closed this. We are currently storing it in the default namespace anyway (since that is the CR namespace) and when we move to other namespaces it makes sense to move this, too.

**Pull request closed without merging**
