### PR TITLE
legacy: Upgrade nginx IC app to 1.2.0

### PR DESCRIPTION
**Pull request by sslavic**
Towards https://github.com/giantswarm/giantswarm/issues/8353

### CODE REVIEW

**Comment by tfussell** [comment]
We're very close to having the cluster-operator+apps ready for 1.16. I think we're going to stick with cluster-operator@0.21.3 for the release so this should be fine for 0.21.4.

**Comment by sslavic** [comment]
@rossf7 it's draft because I still have to test it

**Comment by sslavic** [comment]
Tested on giraffe.

**Comment by cokiengchiara** [comment]
did we test in china?

**Comment by sslavic** [comment]
@rossf7 I've updated changelog entries to cover all included changes - PTAL

**Comment by sslavic** [comment]
@cokiengchiara giraffe is our test environment in China - so yes.

**Comment by sslavic** [comment]
@MarcelMue @tfussell how is 9.1.0 GS release / legacy cluster-operator 0.21.4 looking? Expecting more cluster-operator changes/releases for 9.1.0? I.e. would you mind me merging this for next `0.21.5-dev`? Wouldn't like to create additional work for you e.g. with release notes.

**Comment by MarcelMue** [comment]
We are not expecting more changes here. That said many things this release were quite unexpected :D

Shouldn't stop you from merging though - so go for it.

**Pull request merged**
