### PR TITLE
release 0.22.0

### PR DESCRIPTION
**Pull request by jgsqware**
Signed-off-by: Julien Garcia Gonzalez <julien@giantswarm.io>

PM: https://github.com/giantswarm/giantswarm/issues/7898
Fixes: https://github.com/giantswarm/net-exporter/pull/81

### CODE REVIEW

**Comment by MarcelMue** [comment]
Can someone give me some context here? What should be included and are you creating a release yourself? Should this go into the AWS release?

**Comment by jgsqware** [comment]
@MarcelMue I've updated the top comment with PM and Fix.
We need to release this on KVM legacy only as it's only affecting buffalo currently.
It will be included on master branch whenever you do the release

**Comment by MarcelMue** [comment]
Okay, then you will need to craft a whole new kvm release because we just today released 1.16 for kvm.

**Comment by jgsqware** [comment]
yes it's waiting here: https://github.com/giantswarm/releases/pull/79/

**Pull request merged**
