### PR TITLE
add control plane controller

### PR DESCRIPTION
**Pull request by xh3b4sd**
> {"caller":"github.com/giantswarm/cluster-operator/vendor/github.com/giantswarm/backoff/notifier.go:13","controller":"cluster-operator-control-plane-controller","level":"warning","message":"retrying backoff in '1s' due to error","stack":"[{/go/src/github.com/giantswarm/cluster-operator/vendor/github.com/giantswarm/operatorkit/controller/controller.go:185: } {/go/src/github.com/giantswarm/cluster-operator/vendor/github.com/giantswarm/operatorkit/controller/controller.go:242: } {/go/src/github.com/giantswarm/cluster-operator/vendor/github.com/giantswarm/k8sclient/k8scrdclient/k8scrdclient.go:48: } {/go/src/github.com/giantswarm/cluster-operator/vendor/github.com/giantswarm/k8sclient/k8scrdclient/k8scrdclient.go:85: } {CustomResourceDefinition.apiextensions.k8s.io \"g8scontrolplanes.infrastructure.giantswarm.io\" is invalid: spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:\"v1alpha2\", Served:true, Storage:true, Schema:(*apiextensions.CustomResourceValidation)(0xc014f72af8), Subresources:(*apiextensions.CustomResourceSubresources)(nil), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}}: per-version schemas may not all be set to identical values (top-level validation should be used instead)}]","time":"2020-02-20T17:52:34.454316+00:00"}

### CODE REVIEW

**Comment by xh3b4sd** [comment]
Yeah I thought it is straight forward but then I noticed the weird error which I put into the description. Need to sort this out tomorrow.

**Comment by tfussell** [comment]
I remember running into this issue at one point. Maybe we're using a version without this fix? https://github.com/kubernetes-sigs/controller-tools/pull/322

**Comment by xh3b4sd** [comment]
I talked with Marcel. We found the multi line string defining the schema validation for AWS is "broken", which is why AWS does actually not "fail". The thing is that the validation for the schema checks if all versions given have the same definition. The validation interprets 1 version as "all are the same", which is pretty much unfortunate. Workaround would be to define a second "empty" version to move on. I am not big on providing a PR to the upstream code at this point. I just want to get rid of the multi line string magic as this was rather sloppy as well. It is easier with compiler support anyway.

**Comment by xh3b4sd** [comment]
This thing works now. 🎉

**Pull request merged**
