### PR TITLE
enable vpa for cluster-operator

### PR DESCRIPTION
**Pull request by njuettner**
introducing VPA to cluster-operator to improve handling resources and OOM's

## Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by xh3b4sd** [comment]
Hey Nick, I am a bit off here what this is really doing. Is this about scheduling improvements for the operator itself?

**Review by anvddriesch — APPROVED** [review]

**Comment by njuettner** [comment]
@xh3b4sd so the Vertical Pod Autoscaler is enabled in all CP's by default and we already use it for Prometheus setup. We can use it for the cluster-operator and it will automatically adjust the resources to the actual demand, which is done via collecting metrics.

**Comment by xh3b4sd** [comment]
Does VPA change the number of pods or only the configuration for "requests" and "limits"?

**Comment by calvix** [comment]
VPA changes the request and limits, HPA changes number of pods

**Pull request merged**
