### PR TITLE
Fix how app with and without app suffix are found in catalog

### PR DESCRIPTION
**Pull request by QuentinBisson**
## Checklist

- [ ] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by QuentinBisson** [comment]
@giantswarm/team-honeybadger how is this behavior done in cluster-apps-operator ?

**Comment by QuentinBisson** [comment]
This is causing issues as I renamed kube-state-metrics-app into kube-state-metrics and th defautl catalot now contains both kube-state-metrics-app and kube-state-metrics entries

**Review by whites11 — APPROVED** [review]
LGTM

**Comment by uvegla** [comment]
@QuentinBisson Could you please give a little more context why this is needed? If you renamed the app it makes sense that the older versions are still using the old name in the catalog and the new ones has to be referenced via the new name. I probably don't know this part of the platform well enough, but I think this is not the first renamed app and I don't get it why is this causing an issue now.

**Comment by whites11** [comment]
> @QuentinBisson Could you please give a little more context why this is needed? If you renamed the app it makes sense that the older versions are still using the old name in the catalog and the new ones has to be referenced via the new name. I probably don't know this part of the platform well enough, but I think this is not the first renamed app and I don't get it why is this causing an issue now.

Check 
https://github.com/giantswarm/cluster-operator/blob/master/service/controller/resource/app/desired.go#L258

cluster operator looks at app-name-with-app-suffix first and only if it does not find the app with that name then it fallsback to app-name-without-app-suffix

in your case, the old name is still present, but new app releases are only listed in the new name

so cluster operator will inevitably fail as soon as we'll create a release with a new KSM version

and that's exactly what was happening to me

**Comment by QuentinBisson** [comment]
@whites11 I'm guessing I need to release that in 4.3.0 so I can test it on an 17.x.x release ?

**Comment by QuentinBisson** [comment]
Sure, but we will have to learn at some point :)

**Comment by whites11** [comment]
tested with both KSM 1.11.0 (old name) and 1.22.1 (new name).
Works fine

**Comment by uvegla** [comment]
@QuentinBisson @whites11 Thanks for the fix guys! 🙇🏻

**Pull request merged**
