### PR TITLE
copy clusterconfigmap resource

### PR DESCRIPTION
**Pull request by xh3b4sd**
Simple copy. Refactor and adapt follows.

### CODE REVIEW

**Comment by xh3b4sd** [comment]
I wrote about it but got little to no response: https://gigantic.slack.com/archives/C2MS2VB37/p1565602240140700. May also have been that you were off last week and just missed it. 

We want to unify functionality and use the opportunity to improve the code base. 

* This leads to enabling the Cluster API story and the Node Pools story. 
* This leads to better code internally as we get the chance to revisit certain resource implementations which are a bit off the general alignment. 
* This leads to all providers having support for Node Pools right away. 
* This leads to dropping the intermediate types like `AWSClusterConfig` and the whole concept of "base cluster config" which is all unfortunate and cumbersome. 
* The only drawback is that we need to maintain two code paths simultaneously like we already do in the `aws-operator`. A price I am willing to pay meanwhile considering all the benefits.

**Comment by xh3b4sd** [comment]
Feel free to get in touch with me to talk about this further. I am moving on for now. <3

**Comment by rossf7** [comment]
@xh3b4sd All good and thanks for the explanation. ❤️ 

I dislike the multiple controller design. So implementing this cleanup sooner as part of Node Pools is great.

My concern is just that we also need to work on cluster-operator in Batman. For example we will be removing the chartoperator resource as it moves to app-operator.

But I think this is manageable and so is supporting both code paths during the transition. 👍

**Comment by xh3b4sd** [comment]
Yeah easy. When you drop the resource just drop it in all controllers and do the necessary steps. When there is anything we can also always just talk and figure it out together.

**Pull request merged**
