### PR TITLE
helm/cluster-operator-chart: restore from 81bbd353

### PR DESCRIPTION
**Pull request by mig4**
Towards giantswarm/giantswarm#7719.

Contents restored from commit 81bbd353 using: `git restore --source master^ helm/cluster-operator-chart`

This is needed on master for now to be able to test things.

### CODE REVIEW

**Comment by xh3b4sd** [comment]
Please talk with @kopiczko since he is working on the flattening which is super important to unblock a shitload of projects now. We may do not want to merge this anymore but rather use it as feature branch and close it eventually.

**Comment by mig4** [comment]
@kopiczko updated, something like that?

**Comment by kopiczko** [comment]
For the record: we're keeping this on hold now. Maybe we don't have to merge at all.

**Comment by mig4** [comment]
Hey @kopiczko so at this point this won't be needed right? Can I abandon it?

**Comment by kopiczko** [comment]
💯

**Comment by tfussell** [comment]
Should we close/delete this?

**Comment by MarcelMue** [comment]
Yes :fire:

**Pull request closed without merging**
